### ISSUE TITLE
plugin fail to start on qgis 2.18.9

### ISSUE THREAD

**Issue by antoniusz** [3liz/QgisLayerBoardPlugin#15]
Plugin fail to start with the following error: 

Hiba történt a Python kód végrehajtása közben: 

OverflowError: cannot convert float infinity to integer 
Traceback (most recent call last):
  File "/home/toni/.qgis2/python/plugins/LayerBoard/layer_board.py", line 1061, in run
    self.populateLayerTable( 'raster')
  File "/home/toni/.qgis2/python/plugins/LayerBoard/layer_board.py", line 423, in populateLayerTable
    value = self.getLayerProperty( layer, attr['key'] )
  File "/home/toni/.qgis2/python/plugins/LayerBoard/layer_board.py", line 479, in getLayerProperty
    return int( layer.minimumScale() )
OverflowError: cannot convert float infinity to integer

Python verzió: 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118] 
QGIS verzió 2.18.9 Las Palmas, 7634b0b759

**Comment by Gustry** [comment]
We won't support QGIS 2 anymore.
