### ISSUE TITLE
Uncaught OverflowError: cannot convert float infinity to integer


### ISSUE THREAD

**Issue by olivegak971** [3liz/QgisLayerBoardPlugin#17]
Steps to reproduce
 1. launch plugin 

```
Traceback (most recent call last):
  File "/home/olive/.qgis2/python/plugins/LayerBoard/layer_board.py", line 1061, in run
    self.populateLayerTable( 'raster')
  File "/home/olive/.qgis2/python/plugins/LayerBoard/layer_board.py", line 423, in populateLayerTable
    value = self.getLayerProperty( layer, attr['key'] )
  File "/home/olive/.qgis2/python/plugins/LayerBoard/layer_board.py", line 479, in getLayerProperty
    return int( layer.minimumScale() )
OverflowError: cannot convert float infinity to integer

```
LayerBoard 0.6, QGIS 2.18.13 on Linux 3.16.0-4-amd64

**Comment by rldhont** [comment]
Can you publish a new version ?

**Comment by mdouchin** [comment]
I will try this afternoon

**Comment by mdouchin** [comment]
Done https://plugins.qgis.org/plugins/LayerBoard/
