### ISSUE TITLE
   OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by Capex837** [3liz/QgisLayerBoardPlugin#28]
Hello everybody,

I am trying to interpolate with TIN method a set of XYZ data on QGUS, but once created the layer, i try to run the Interpolation and this errorappears:

2023-11-27T12:10:09     WARNING    Traceback (most recent call last):
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 305, in pixelSizeChanged
              rows = max(round(self.extent.height() / cell_size) + 1, 1)
             OverflowError: cannot convert float infinity to integer
             
2023-11-27T12:10:09     WARNING    Traceback (most recent call last):
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\ProcessingPlugin.py", line 428, in executeAlgorithm
              dlg = AlgorithmDialog(alg, in_place, iface.mainWindow())
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 69, in __init__
              self.setMainWidget(self.getParametersPanel(alg, self))
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 93, in getParametersPanel
              panel = ParametersPanel(parent, alg, self.in_place, self.active_layer)
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\gui\ParametersPanel.py", line 69, in __init__
              self.initWidgets()
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\gui\ParametersPanel.py", line 197, in initWidgets
              wrapper.postInitialize(list(self.wrappers.values()))
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 383, in postInitialize
              self.setLayers(wrapper.parameterValue())
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 393, in setLayers
              self.widget.setLayers(layersData)
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 285, in setLayers
              self.pixelSizeChanged()
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 305, in pixelSizeChanged
              rows = max(round(self.extent.height() / cell_size) + 1, 1)
             OverflowError: cannot convert float infinity to integer

This is an example of the data 

[Sample.csv](https://github.com/3liz/QgisLayerBoardPlugin/files/13473402/Sample.csv)

Can you give me a hand?
thanks in advance

**Comment by Gustry** [comment]
According to your description and the error you have provided, this is not related to "Layer board" plugin, no ?
You should use https://gis.stackexchange.com/ for asking generic questions on QGIS or https://github.com/qgis/QGIS if you think you have a real bug.

First, check your QGIS version you are using, you must use a maintained version of QGIS. https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule
